### ISSUE TITLE
How to sync SF custom objects?

### ISSUE THREAD

**Issue by awartani** [mlsmithjr/gurglefish#1]
Thank you, this tool is great. 

I need your help on how to resolve the following issue.

I got the following error when I ran the script for a bunch of custom fields in Salesforce:

```
Process SyncThread-1:
Traceback (most recent call last):
  File "/opt/python3.7/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/root/.local/share/virtualenvs/app-xt2hxg7t/lib/python3.7/site-packages/gurglefish/sfexport.py", line 147, in run
    allow_drop=tabledef.auto_drop_columns)
  File "/root/.local/share/virtualenvs/app-xt2hxg7t/lib/python3.7/site-packages/gurglefish/schema.py", line 170, in update_sobject_definition
    self.driver.maintain_indexes(sobject_name, SObjectFields(new_field_defs))
  File "/root/.local/share/virtualenvs/app-xt2hxg7t/lib/python3.7/site-packages/gurglefish/objects/sobject.py", line 95, in __init__
    if field.type == 'address':
AttributeError: 'SObjectField' object has no attribute 'type'
```

**Comment by mlsmithjr** [comment]
Thanks for this.  Bug fixed and pushed as version 1.1.9

**Comment by awartani** [comment]
That's awesome, I'll give it a try today

**Comment by awartani** [comment]
@mlsmithjr great work, it worked.
