### ISSUE TITLE
name 'tm' is not defined

### ISSUE THREAD

**Issue by awartani** [mlsmithjr/gurglefish#2]
Do you have any idea on how to resolve this issue?
```
Process SyncThread-1:
Traceback (most recent call last):
  File "/opt/python3.7/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/root/.local/share/virtualenvs/app-xt2hxg7t/lib/python3.7/site-packages/gurglefish/sfexport.py", line 215, in run
    raise ex
  File "/root/.local/share/virtualenvs/app-xt2hxg7t/lib/python3.7/site-packages/gurglefish/sfexport.py", line 178, in run
    trec = xlate_handler.parse(rec)
  File "/var/lib/gurglefish/db/prod/schema/postpartum_visit__c/postpartum_visit__c_Transform.py", line 22, in parse
    result["First_Visit_Time__c"] = tm(rec, "First_Visit_Time__c", fieldlen=0)
NameError: name 'tm' is not defined
```

Thanks!

**Comment by mlsmithjr** [comment]
Thanks for the report.  It's a problem with decoding Time column types.  I
should have it patched and the package updated by tomorrow (Friday).

**Comment by mlsmithjr** [comment]
Note: I was able to get this fix pushed up tonight. You will need to drop
the affected table in postgres so that the next --sync will reinitialize it
and the generated code.  After that your time fields should process
normally.

**Comment by awartani** [comment]
That's awesome, I'll give it a try today

**Comment by awartani** [comment]
@mlsmithjr thanks, it worked.
for reference, I had to run:
```
gurglefish prod --schema <object-name>
```
